spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    generate-unique-name: false
  cloud:
    config:
      label: main
      name: product-service-dev
#server:
#  port: 8081
eureka:
  instance:
    prefer-ip-address: true



